import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Joy's Portfolio",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import { ThemeProvider } from "next-themes";

export default function Layout({ children }) {
  return (
    <html suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
        attribute="data-theme"     // 👈 adds data-theme to <html>
        defaultTheme="dark"        // 👈 defaults to dark
        enableSystem={true} 
        >
          {children}</ThemeProvider>
      </body>
    </html>
  )
}


// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <div className="flex flex-col min-h-screen">
//           <main className="flex-grow">{children}</main>
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }